---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: igorf211/pcf-terraform
    tag: "latest"
inputs:
- name: git-assets

run:
  path: git-assets/ci/tasks/apply-terraform-script
